#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

branches:
  only:
    - develop
    - test_attributes

skip_commits:
  message: /\[skip ci\]|\[ci skip\]|\[skip appveyor\]|\[ci appveyor\]/
  files:
    - .travis*
    - data/
    - '*.md'

clone_folder: c:\projects\myproject

# fetch repository as zip archive
shallow_clone: true 

image:
  - Visual Studio 2015
  - Visual Studio 2017

configuration:
  - Release
  - Debug

environment:
  CMAKE_TOOLCHAIN_FILE: -DCMAKE_TOOLCHAIN_FILE="C:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake"
  matrix:
    - arch: x64

build:
  parallel: true
  verbosity: minimal

# skip unsupported combinations
init:
  - echo %arch%
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - if "%arch%"=="x64" (set TARGET_PLATFORM= Win64)
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" (set GENERATOR="Visual Studio 15 2017%TARGET_PLATFORM%" && set QT_DIR="C:\Qt\5.10.1\msvc2017_64\lib\cmake\Qt5")
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" (set GENERATOR="Visual Studio 14 2015%TARGET_PLATFORM%" && set QT_DIR="C:\Qt\5.10.1\msvc2015_64\lib\cmake\Qt5")
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" (set GENERATOR="Visual Studio 12 2013%TARGET_PLATFORM%" && set QT_DIR="C:\Qt\5.8\msvc2013_64\lib\cmake\Qt5")
  - echo %GENERATOR%
  - echo %QT_DIR%

install:
  - vcpkg remove --outdated --recurse
  - vcpkg install --recurse
        zlib
        eigen3
        tinyxml2
        --triplet %arch%-windows

build_script:
  - md build
  - cd build
  - cmake --version
  - cmake -Wno-dev -Wno-deprecated -G %GENERATOR% .. -DCMAKE_SUPPRESS_REGENERATION=1 %CMAKE_TOOLCHAIN_FILE% -DQt5_DIR=%QT_DIR% -DCGOGN_BUILD_TESTS=ON -DCGOGN_BUILD_EXAMPLES=ON -DCGOGN_BUILD_BENCHS=ON 
  - cmake --build . --config "%CONFIGURATION%" -- /verbosity:minimal
  - cmake --build . --config "%CONFIGURATION%" --target RUN_TESTS -- /verbosity:minimal
  - cmake --build . --config "%CONFIGURATION%" --target INSTALL -- /verbosity:minimal
